name = 'NavHive'
license = 'Apache 2.0'
licenselink = 'https://github.com/idevsig/navhive/LICENSE'
description = 'NavHive theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/idevsig/navhive'

# If you have a running demo of the theme
demosite = 'https://navhive.ooos.top'

# Taxonomy terms
tags = ['navigation', 'light', 'dark' ]
features = ['some', 'awesome', 'features']

[author]
  name = 'Jetsung Chan'
  homepage = 'https://github.com/jetsung'
